title: sirrachhha
author: Bennie
email: benazirt@redlodge.k12.mt.us
description: > # this means to ignore newlines until "baseurl:"
  basically my website
# social links
twitter_username: elon musk # DO NOT include the @ character, or else the build will fail!
github_username:  benniethedeveloper # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minim–∞.

